#!/bin/sh

echo "got INPUT_COMMIT: ${INPUT_COMMIT}"
echo "got INPUT_TAG: ${INPUT_TAG}"
echo "got INPUT_TRUSTED_SIGNER_PUBKEY: ${INPUT_TRUSTED_SIGNER_PUBKEY}"
echo "got INPUT_PUBKEY_URL: ${INPUT_PUBKEY_URL}"
echo "got INPUT_PUBKEY_URL_HASH: ${INPUT_PUBKEY_URL_HASH}"
