name: Verify Action

on:
  push:
  repository_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Verify
        uses: 4x0v7/ghaction-verify-gitobj@v0.1.3
        with:
          repo: https://github.com/github/platform-samples
          ref: 37ae55f6942b62b6801d1656d7b51e6aaa9aab27
