name: Test Action

on:
  push:
  repository_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        # Commit & tag combos
        - test_type: inputs_has_commit_and_tag_throws
          input_repo: https://github.com/github/platform-samples
          input_tag: v0.0.0
          input_commit: 37ae55f6
        - test_type: inputs_has_tag_only_passes
          input_tag: afaf2f02650a6854f45cbf5fca7142b7c44ef51b
        - test_type: inputs_has_commit_only_passes
          input_commit: afaf2f02650a6854f45cbf5fca7142b7c44ef51b
        - test_type: inputs_has_no_commit_and_tag_throws
          input_tag: ''
          input_commit: ''

        # Key & url combos
        - test_type: inputs_has_key_and_url_throws
          input_repo: https://github.com/github/platform-samples
          input_commit: 37ae55f6
          input_pubkey: 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23 #fingerprint
          input_pubkey_url: https://github.com/web-flow.gpg
        - test_type: inputs_has_url_only_passes
          input_repo: https://github.com/github/platform-samples
          input_commit: 37ae55f6
          input_pubkey_url: https://github.com/web-flow.gpg
        - test_type: inputs_has_key_only_passes
          input_repo: https://github.com/github/platform-samples
          input_commit: 37ae55f6
          input_pubkey: 4AEE18F83AFDEB23 #longkey
        - test_type: inputs_has_no_key_and_url_throws
          input_repo: https://github.com/github/platform-samples
          input_commit: 37ae55f6
          input_pubkey: ''
          input_pubkey_url: ''

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
      with:
        install: true
      id: buildx
    - name: Build
      run: |
        docker build -t action-runner .
    - uses: kohlerdominik/docker-run-action@v1
      env:
        INPUT_REPO: ${{ matrix.input_repo }}
        INPUT_REF: ${{ matrix.input_ref }}
        INPUT_TAG: ${{ matrix.input_tag }}
        INPUT_PUBKEY: ${{ matrix.input_pubkey }}
        INPUT_PUBKEY_URL: ${{ matrix.input_pubkey_url }}
      with:
        image: action-runner
        environment: |
          INPUT_REPO=${INPUT_REPO}
          INPUT_REF=${INPUT_REF}
          INPUT_TAG=${INPUT_TAG}
          INPUT_PUBKEY=${INPUT_PUBKEY}
          INPUT_PUBKEY_URL=${INPUT_PUBKEY_URL}
        run: |
          echo "Running tests"
